[package]
name = "Bank-Communication"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-web = "4.11.0"
tokio = { version = "1.48.0", features = ["full"] }

# 2. Xử lý chuẩn ISO 8583
# Standard library for parsing 8583
iso8583 = "0.1.0"
iso8583_rs = "0.1.10"
quick-xml = { version = "0.38.3", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
config = "0.15.18"
thiserror = "2.0.17"
anyhow = "1.0.100"
chrono = { version = "0.4.42", features = ["serde"] }

ring = "0.17.14"
